name: CI

on:
  pull_request:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}


      - name: Pre-build fresh Docker images cache
        run: make docker.build.cache no-cache=yes


      - name: Test Docker images
        run: |
          # Enable experimental features of Docker Daemon to run multi-arch
          # images.
          echo "$(cat /etc/docker/daemon.json)" '{"experimental": true}' \
          | jq --slurp 'reduce .[] as $item ({}; . * $item)' \
          | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

          make test.docker platforms=@all build=yes


      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GCR_BOT_PAT }}

      - name: Login to Quay.io
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: instrumentisto+bot
          password: ${{ secrets.QUAYIO_ROBOT_TOKEN }}

      - name: Login to Docker Hub
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/login-action@v1
        with:
          username: instrumentistobot
          password: ${{ secrets.DOCKERHUB_BOT_PASS }}

      - name: Publish Docker images
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        run: make docker.push

      - name: Update README on Quay.io
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAYIO_API_TOKEN }}
        with:
          provider: quay
          destination_container_repo: quay.io/instrumentisto/haraka
          readme_file: README.md

      - name: Update README on Docker Hub
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: instrumentistobot
          DOCKER_PASS: ${{ secrets.DOCKERHUB_BOT_PASS }}
        with:
          provider: dockerhub
          destination_container_repo: instrumentisto/haraka
          readme_file: README.md

      # On GitHub Container Registry README is automatically updated on pushes.

      - name: Parse release version from Git tag
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        id: release
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Parse CHANGELOG link
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        id: changelog
        run: echo ::set-output name=LINK::https://github.com/${{ github.repository }}/blob/v${{ steps.release.outputs.VERSION }}/CHANGELOG.md#$(sed -n '/^## \[${{ steps.release.outputs.VERSION }}\]/{s/^## \[\(.*\)\][^0-9]*\([0-9].*\)/\1--\2/;s/[^0-9a-z-]*//g;p;}' CHANGELOG.md)

      - name: Release on GitHub
        if: ${{ github.event_name == 'push'
                && startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.release.outputs.VERSION }}
          release_name: ${{ steps.release.outputs.VERSION }}
          body: |
            [Changelog](${{ steps.changelog.outputs.LINK }})
