name: CI

on:
  pull_request:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Available Docker buildx platforms
        run: echo ${{ steps.buildx.outputs.platforms }}


      - name: Pre-build fresh Docker images cache
        run: make docker.build.cache no-cache=yes


      - name: Test Docker images
        run: |
          # Enable experimental features of Docker Daemon to run multi-arch
          # images.
          echo "$(cat /etc/docker/daemon.json)" '{"experimental": true}' \
          | jq --slurp 'reduce .[] as $item ({}; . * $item)' \
          | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

          make test.docker platforms=@all build=yes
